# file: .github/workflows/hello-world.yml
name: workflow-hexlet-ci
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.484d7353-53e8-40e9-bb83-72a065569b58 }}
  first-job-build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v2
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - run: make setup
      - run: make test
      - run: make lint
