# file: .github/workflows/hello-world.yml
name: workflow-hexlet-ci
on: push
jobs:
  first-job-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make setup
      - run: make test
      - run: make lint
      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
