# file: .github/workflows/hello-world.yml
name: workflow-hexlet-ci
on: push
jobs:
  first-job-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make setup
      - run: make test
      - run: make lint
      - uses: snyk/actions/node@v0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.484d7353-53e8-40e9-bb83-72a065569b58 }}
